// scripted/written by Robert Bopko (github.com/zeroznet) with Boba Bott (Claude Haiku 4.5)

package wsl

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWSL2GatewayIP_FromTempResolvConf(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "resolv.conf")
	require.NoError(t, os.WriteFile(p, []byte("# automatically generated by WSL\nnameserver 172.20.16.1\noptions edns0\n"), 0o644))

	got, err := wsl2GatewayIPFrom(p)
	require.NoError(t, err)
	assert.Equal(t, "172.20.16.1", got)
}

func TestWSL2GatewayIP_NoNameserver(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "resolv.conf")
	require.NoError(t, os.WriteFile(p, []byte("# automatically generated by WSL\n"), 0o644))

	_, err := wsl2GatewayIPFrom(p)
	assert.Error(t, err)
}

func TestWSL2GatewayIP_NoMarker_RejectsUserManagedFile(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "resolv.conf")
	// User-edited resolv.conf with a public resolver first — exactly the
	// case we must refuse, so we don't redirect 1.1.1.1 traffic by accident.
	require.NoError(t, os.WriteFile(p, []byte("nameserver 1.1.1.1\nnameserver 8.8.8.8\n"), 0o644))

	_, err := wsl2GatewayIPFrom(p)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "marker absent")
}
