// scripted/written by Robert Bopko (github.com/zeroznet) with Boba Bott (Claude Haiku 4.5)

// Package wsl reads the WSL2 NAT gateway IP from resolv.conf with a
// safety check: only files carrying WSL's auto-generated marker comment
// are trusted. A user-edited resolv.conf with a public resolver first
// would otherwise silently misdirect our NAT redirect.
package wsl

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// WSL2GatewayIP returns the WSL2 NAT gateway IP. It reads
// /mnt/wsl/resolv.conf first (the single mount WSL exposes across all
// distros), falls back to /etc/resolv.conf. The first `nameserver` line
// is the gateway — but only if the file carries WSL's auto-generated
// marker comment. A user-edited resolv.conf may have a public resolver
// like 1.1.1.1 first, which would silently misdirect our NAT redirect;
// in that case we refuse and the caller must set WSL2_GATEWAY_IP
// explicitly.
func WSL2GatewayIP() (string, error) {
	var lastErr error
	for _, p := range []string{"/mnt/wsl/resolv.conf", "/etc/resolv.conf"} {
		ip, err := wsl2GatewayIPFrom(p)
		if err == nil {
			return ip, nil
		}
		lastErr = err
	}
	return "", fmt.Errorf("autodetect WSL2 gateway: %w (set WSL2_GATEWAY_IP to override)", lastErr)
}

// autoGenMarker is the comment WSL writes at the top of resolv.conf when
// it manages the file. If it's absent, the file has been customized and
// we can't trust the first nameserver to be the WSL2 NAT gateway.
const autoGenMarker = "automatically generated by WSL"

func wsl2GatewayIPFrom(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	hasMarker := false
	var firstNS string
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "#") && strings.Contains(line, autoGenMarker) {
			hasMarker = true
			continue
		}
		if firstNS != "" {
			continue
		}
		if !strings.HasPrefix(line, "nameserver ") {
			continue
		}
		ns := strings.TrimSpace(strings.TrimPrefix(line, "nameserver "))
		if ns != "" {
			firstNS = ns
		}
	}
	if !hasMarker {
		return "", fmt.Errorf("%s: WSL auto-generated marker absent (file appears user-managed)", path)
	}
	if firstNS == "" {
		return "", fmt.Errorf("%s: no nameserver line found", path)
	}
	return firstNS, nil
}
